import os

import utils

class SimulatedGenome:
    """ Simulated genome data generated by simuG  """

    def __init__(self, name, genome_path, snp_table_path, snp_vcf_path, indel_vcf_path):
        # Validate
        utils.assert_path_exists(genome_path)
        utils.assert_path_exists(snp_table_path)
        utils.assert_path_exists(snp_vcf_path)
        utils.assert_path_exists(indel_vcf_path)

        # Assign
        self.genome_path = genome_path
        self.snp_table_path = snp_table_path
        self.snp_vcf_path = snp_vcf_path
        self.indel_vcf_path = indel_vcf_path
        
        self.name = name
